### ISSUE TITLE
'Supervisor' object has no attribute '_children'

### ISSUE THREAD

**Issue by andresriancho** [celery/billiard#111]
I'm running a rather complex celery task which is giving me this error:

```
'Supervisor' object has no attribute '_children'
```

It seems to be related to http://bugs.python.org/issue14881 , and seems to make sense since `Supervisor` is a `threading.Thread` and is doing some stuff with pools.

These are my versions:

```
celery==3.1.6
billiard==3.3.0.17
```

Celery is started using the following command:

```
/usr/local/bin/celery worker -A octopus -l info -Q scan,default --beat --no-color
```

Any ideas on how to better debug this? Have you seen it before? Workarounds? Fixes?

**Comment by d4wner** [comment]
thx so much, I solved the problem with this issue.
