### ISSUE TITLE
Consider porting python 3.4 forkserver into billiard

### ISSUE THREAD

**Issue by jamescasbon** [celery/billiard#127]
There are quite a few people, including [Ipython notebook users](https://github.com/ipython/ipython/issues/6109) who could benefit from this [feature](https://docs.python.org/3/whatsnew/3.4.html#whatsnew-multiprocessing-no-fork).  Is billiard the right place for this?

I note that [subprocess32](http://code.google.com/p/python-subprocess32/) already has the c extension backported that does the forking.

**Comment by ask** [comment]
Forkserver is in master now, but I haven't actually tried it
