### ISSUE TITLE
timeout_callback not triggered for apply_async

### ISSUE THREAD

**Issue by benb42** [celery/billiard#156]
The timeout_callback does not seem to be working . In the following code the timeout of 3s works ok, but I don't get the callback triggered. Tried this with Billiard 3.3.0.20 on Windows 7 with Python 2.7.9 / 3.4 and Mac OS X 10.10.3 with Python 2.7.9.

```
import billiard as mp
import time
import random

def fun_cube(x):
    sleep_time = random.uniform(1,5)
    time.sleep(sleep_time)

    return x,x**3,sleep_time

def done(x):
    print '\nThe cube of %s is %s.' %(x[0],x[1])

def timeout():
    print 'Timeout triggered!'

if __name__ == '__main__':
    pool = mp.Pool(processes=4)
    for i in range(1,10):
        pool.apply_async(func=fun_cube,args=(i,), callback=done, timeout_callback=timeout, timeout=3)
    pool.close()
    pool.join()
```

**Comment by ask** [comment]
Hey! The timeout handler thread is not started unless you specify a default timeout for the Pool.

e.g `Pool(timeout=10e8)`
