### ISSUE TITLE
Celery workers halt on _recv

### ISSUE THREAD

**Issue by Nihn** [celery/billiard#158]
Sometimes our celery workers freeze at:
https://github.com/celery/billiard/blob/master/billiard/pool.py#L417
It would be good to provide some kind of timeout here.

**Comment by thedrow** [comment]
@ask Could this be related to any of the issues that reported that celery stopped consuming tasks?
Do you think we should add a timer where @Nihn pointed or at https://github.com/celery/billiard/blob/13d7f80252a332999f46012853ffb27309357cc6/billiard/connection.py#L225

**Comment by ask** [comment]
Being stuck in recv simply means the child process is waiting for more work!
It's normal behavior, if you are debugging a problem you should probably find out why there is no work.

**Comment by Nihn** [comment]
Oh, thanks for explanation. I was debugging situation when workers stopped working and no task were consumed and I thought that this is the case.

**Comment by thedrow** [comment]
@Nihn It could be but it is unlikely. We'd like to get more information if possible.

**Comment by Nihn** [comment]
@thedrow for some time I haven't got this problem. If it happens again I will try to provide more details. Thanks for help :).
