### ISSUE TITLE
Add a CI process for Windows

### ISSUE THREAD

**Issue by thedrow** [celery/billiard#161]
Since this project has some code paths that are Windows specific it is worthwhile to set up a CI process for Windows.
I have enabled [appveyor](http://www.appveyor.com/) for this purpose but I have not written the build script yet.

**Comment by ask** [comment]
https://ci.appveyor.com/project/ask/billiard

**Comment by thedrow** [comment]
Shouldn't be for celery/billiard? Also, awesome stuff :)
