### ISSUE TITLE
CHANGES.txt is missing changelog for 3.3.0.18 and newer

### ISSUE THREAD

**Issue by edmorley** [celery/billiard#164]
https://github.com/celery/billiard/blob/master/CHANGES.txt does not include entries for 3.3.0.18, 3.3.0.19 and 3.3.0.20, unlike the changelog in the description here:
https://pypi.python.org/pypi/billiard

**Comment by thedrow** [comment]
Feel free to submit a pull request.
Otherwise I'll get to it.
