### ISSUE TITLE
Issue with createLock

### ISSUE THREAD

**Issue by cbron** [celery/billiard#165]
I'm starting celery with this: `venv/bin/celery -A app.lib.tasks.celery worker -Q default`

And now I'm getting this error: 

Traceback (most recent call last):
  File "venv/local/lib/python2.7/site-packages/billiard/process.py", line 280, in _bootstrap
    handler.createLock()
AttributeError: 'ProcessAwareLogger' object has no attribute 'createLock'
Unrecoverable error: WorkerLostError('Could not start worker processes',)

billiard version: 3.3.0.19
celery version: 3.1.17

**Comment by cbron** [comment]
Seems to be an issue with a logging module, specifically logentries.

**Comment by gdude2002** [comment]
In #223 I seem to be having a similar issue - although it's with Python 3.6 instead.

Did you figure out a way around this?
