### ISSUE TITLE
Task raised exception: 'Terminated(9,)'

### ISSUE THREAD

**Issue by rafaelnovello** [celery/billiard#167]
Hi!

Sometimes one of my tasks is terminated with the following error:
```
Task tasks.start_campaigns with id 5c1b7b74-d41f-4f2d-86e2-d4655ec58174 raised exception:
'Terminated(9,)'


Task was called with args: [] kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 961, in _join_exited_workers
    raise Terminated(-exitcodes[worker_pid])
Terminated: 9
```
At first I thought it would be lack of space in memory but is not the problem. Can anyone help?

I'm running:
Ubuntu 12.04
Python 2.7 
Celery 3.0.24
billiard 2.7.3.34

**Comment by ask** [comment]
It just means your process was signalled with SIGKILL.

Maybe there was a hard timeout associated with it, or `revoke+terminate` was used.  Otherwise celery wouldn't send this signal, and it must have been sent by someone/something else.
