### ISSUE TITLE
wheels for billard

### ISSUE THREAD

**Issue by srkunze** [celery/billiard#171]
Do you consider providing Python wheels for billiard? http://pythonwheels.com/

**Comment by ask** [comment]
Yeah, I would like to, but it's more useful for Windows, and I don't currently have an installation here.

Need to set up some way to build wheels for different platforms.

**Comment by ask** [comment]
Windows wheels are now available for 3.3.0.22

**Comment by srkunze** [comment]
Nice! Thank you. :)
