### ISSUE TITLE
unable to import billard as package when building a new amazon-ami

### ISSUE THREAD

**Issue by ysfjwd** [celery/billiard#177]
i am building a new amazon instance with python 2.7.10 as default.
after i have ran my machine provisioning scripts and the moment of truth arrives, celery gave me an import so i debugged the problem to billard.

the package appears to be in the correct path i.e.

```bash
sudo find -name "billiard"
./srv/ia-live/lib64/python2.7/dist-packages/billiard
```

where ia-live is the path of my virtualenv. checking the path in via python virtualenv execuatable

```python
import sys
sys.path

['',
 '/srv/ia-live/bin',
 '/srv/ia-live/src/django-devserver-redux-master',
 '/usr/lib/python2.7',
 '/srv/ia-live/local/lib64/python2.7/site-packages',
 '/srv/ia-live/local/lib/python2.7/site-packages',
 '/srv/ia-live/lib64/python2.7',
 '/srv/ia-live/lib/python2.7',
 '/srv/ia-live/lib64/python2.7/site-packages',
 '/srv/ia-live/lib/python2.7/site-packages',
 '/srv/ia-live/lib64/python2.7/lib-dynload',
 '/srv/ia-live/local/lib/python2.7/dist-packages',
 '/srv/ia-live/local/lib/python2.7/dist-packages',
 '/srv/ia-live/lib/python2.7/dist-packages',
 '/usr/lib64/python2.7',
 '/usr/lib/python2.7',
 '/srv/ia-live/local/lib/python2.7/dist-packages/IPython/extensions',
 '/home/ec2-user/.ipython']
```

which appears to be correct, but when i do

```python
import billiard
ImportError: No module named billiard
```

i don't understand why there could be problem

**Comment by ysfjwd** [comment]
i was able to identify the problem. 
first i upgraded the system pip to latest version
then i upgrade virtualenv to the latest version

and the i ran /usr/bin/virtualenv .. to hard run the virtualenv i required and it solved the problem for me

hope it helps somebody else too.

**Comment by juanrgon** [comment]
@ysfjwd This worked for me too. I had to upgrade my system pip, upgrade virtualenv, then delete my old virtualenv and create a new one
