### ISSUE TITLE
Missing tag v3.5.0.2

### ISSUE THREAD

**Issue by jakirkham** [celery/billiard#199]
There doesn't seem to be a tag for `v3.5.0.2`. Could one please be added? 😄

**Comment by thedrow** [comment]
@auvipy Care to pick this one up?

**Comment by auvipy** [comment]
I;m not quite sure how to do that as there is now 3.5.0.3 tag already! any clues?

**Comment by thedrow** [comment]
Just checkout the commit https://github.com/celery/billiard/commit/40d449d20264925b89b84e6f1425de83babccc5a and `git tag v3.5.0.2 -m "Fixes #199" && git push v3.5.0.2`

**Comment by auvipy** [comment]
OK :+1:

**Comment by auvipy** [comment]
https://github.com/celery/billiard/releases/tag/v3.5.0.2 I hope its done :dagger:

**Comment by jakirkham** [comment]
Thanks.
