### ISSUE TITLE
Celery incompatible with Ansible 

### ISSUE THREAD

**Issue by dvannatter** [celery/billiard#203]
When using both Billard (by Celery) and the standard process.py module (by Ansible), there are some compatibility issues because they both define _current_process, but they define it differently. In particular, the standard process.py tries to get _current_process._authkey, but this is not an attribute of the Billard version of the _current_process which stores the authkey in  _current_process._config['authkey']

**Comment by auvipy** [comment]
https://github.com/celery/billiard/commit/4f9a9b56ade9c232f83f29ca03a22f9ccf275a1d
