### ISSUE TITLE
Please release for compatibility with 2.7

### ISSUE THREAD

**Issue by 23doors** [celery/billiard#222]
Encountered compatibility issues with 2.7 and found that they were already fixed in: https://github.com/celery/billiard/pull/202 and https://github.com/celery/billiard/commit/d0be0308a9dfd17c28277bb582edcf009ecd3153

Please make a new release to include these as right now 2.7 compatibility is kind of broken in 4.x celery.

**Comment by auvipy** [comment]
https://github.com/celery/billiard/releases/tag/v3.5.0.3 should fix that
