### ISSUE TITLE
Provide wheel distributions for all platforms

### ISSUE THREAD

**Issue by edmorley** [celery/billiard#232]
Hi!

The [3.5.0.3 release](https://pypi.python.org/pypi/billiard/3.5.0.3) was available as:
* sdist
* python 3 pure python wheel

...for [3.5.0.2](https://pypi.python.org/pypi/billiard/3.5.0.2):
* sdist
* python 3 pure python wheel
* python 2.7 wheel for OS X
* several python 2.7 wheels for Windows

...for [3.5.0.1](https://pypi.python.org/pypi/billiard/3.5.0.1):
* sdist
* python 2.7 wheel for OS X

It would be great to:
a) Ensure consistency in which wheels are offered for each release
b) Add support for Linux wheels via the new manylinux1 ABI

The former is probably best achieved using Travis/appveyor - the [simplejson](https://github.com/simplejson/simplejson) repo has some useful looking scripts for this.

For the latter, it's still early days, but hopefully these can help:
https://www.python.org/dev/peps/pep-0513/
https://github.com/pypa/python-manylinux-demo

Many thanks :-)

**Comment by auvipy** [comment]
I believe this should be addressed before next minor release
