### ISSUE TITLE
Could not connect, 0 attempts left

### ISSUE THREAD

**Issue by davidmir** [celery/billiard#246]
Hi,

I am periodically seeing the following errors in the logs:

`[2018-06-15 15:01:32,363: ERROR/ForkPoolWorker-5] Connection to 10.0.0.6:5672 failed: timeout
[2018-06-15 15:01:32,363: WARNING/ForkPoolWorker-5] Could not connect, 0 attempts left`

I'm using celery 4.1.0 with RabbitMQ connection (amqp=2.2.2).
What happens to the celery process in these situations (is it killed and the task is lost, or is it able to recover)? What could be causing this situation?

Thanks.

**Comment by thedrow** [comment]
It seems that the IPC socket failed to connect to the workers. I have no idea why though based on the details you provided me on this issue.
