### ISSUE TITLE
max_memory_per_child doesn't work on Windows (with a fix)

### ISSUE THREAD

**Issue by genben** [celery/billiard#250]
Parameter `max_memory_per_child` is not passed to `Worker.__reduce__` method:

https://github.com/celery/billiard/blob/471d38e72df9cf380be90f89d0dde2735073b851/billiard/pool.py#L267-L272

As a result, on Windows, where forking is made via multi-processing, a child process doesn't receive such parameter. So, an automatic restart of a worker after reaching a memory limit doesn't happen.

To fix this issue, the method `Worker.__reduce__()` should be modified to:

```
    def __reduce__(self):
        return self.__class__, (
            self.inq, self.outq, self.synq, self.initializer,
            self.initargs, self.maxtasks, self._shutdown, self.on_exit,
            self.sigprotection, self.wrap_exception, self.max_memory_per_child
        )
```

**Comment by auvipy** [comment]
please feel free to send a pr

**Comment by genben** [comment]
Pull request submitted: #251

**Comment by genben** [comment]
Pull request is merged to master in https://github.com/celery/billiard/commit/0e4e7f58618e703e56f1fad2f73076dc1af20ce6

Please close this ticket.
