### ISSUE TITLE
max_memory_per_child reached log is ERROR level, should be INFO

### ISSUE THREAD

**Issue by yuvalbar** [celery/billiard#255]
When Celery recycles a Celery worker, it emits this log: 

```
​ERROR/ForkPoolWorker-587] child process exiting after exceeding memory limit (421812KiB / 300000KiB)
```

It happens in `pool.py:379`:
``` Python
                    if used_kb > 0 and used_kb > max_memory_per_child:
                        error(MAXMEM_USED_FMT.format(
                            used_kb, max_memory_per_child))
```

This is not actually an error, but an expected situation where I want to recycle workers as there is no other way to reduce their memory footprint. It should probably be lowered to INFO - I'm willing to open a PR if that's acceptable. Plz let me know - Thanks!

**Comment by auvipy** [comment]
pr welcome

**Comment by truthdoug** [comment]
PR added #272

**Comment by matteius** [comment]
In my preference this would be a log.warning error.  With no memory leaking and an appropriately picked value, generally this condition should not be reached so a warning level feels appropriate.  I agree its not an error because its a feature of the app to restart the worker at that point.

**Comment by thedrow** [comment]
@matteius See PR.
