### ISSUE TITLE
TypeError: argument must be an int, or have a fileno() method.

### ISSUE THREAD

**Issue by paulocheque** [celery/billiard#270]
`billiard==3.5.0.5`
`OSX 10.14.2`
`Py 3.6`

Hello, any ideas about this exception?
Thanks in advance!

```
  File "/env/lib/python3.6/site-packages/billiard/managers.py", line 588, in __exit__
    self.shutdown()
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/env/lib/python3.6/site-packages/billiard/managers.py", line 612, in _finalize_manager
    process.join(timeout=0.1)
  File "/env/lib/python3.6/site-packages/billiard/process.py", line 148, in join
    res = self._popen.wait(timeout)
  File "/env/lib/python3.6/site-packages/billiard/popen_fork.py", line 54, in wait
    if not wait([self.sentinel], timeout):
  File "/env/lib/python3.6/site-packages/billiard/connection.py", line 998, in wait
    return _poll(object_list, timeout)
  File "/env/lib/python3.6/site-packages/billiard/connection.py", line 970, in _poll
    pollster.register(fd, select.POLLIN)
TypeError: argument must be an int, or have a fileno() method.
```

**Comment by auvipy** [comment]
could you try new 3.6.0 release?

**Comment by paulocheque** [comment]
celery 4.2.1 has requirement billiard<3.6.0,>=3.5.0.2, but you'll have billiard 3.6.0.0 which is incompatible.

**Comment by clokep** [comment]
We're running celery 4.2.1 on billiard 3.6.0 and it works fine. 👍

**Comment by clokep** [comment]
@auvipy Not sure why you closed this, I was just responding to @paulocheque saying that you cannot use billiard 3.6.0 with celery 4.2.1. This seems like we should be updating the requirements in Celery though...

**Comment by liuyoyi** [comment]
@paulocheque Have you solved this problem?

**Comment by paulocheque** [comment]
I just forced to use the newest version of Celery and Billiard but I don't think the problem was completely solved.

Also, yes, they really need to release a new version to avoid this kind of lib dependency error.

**Comment by KevinPoole** [comment]
Hey all, anybody know what the latest is with this?

I am using:
```
billiard==3.6.3.0
celery==4.4.7
```

and getting this when I call `proc.join(timeout=1)`

**Comment by Alphare** [comment]
Simple reproduction using `billiard==3.6.4.0`:

```python
from billiard import Queue, Process
import time

errors: Queue = Queue()
process = Process(target=lambda: time.sleep(5))
process.start()
process.join(1)
process.join(2)  # Fails here
```

**Comment by benmosher** [comment]
`multiprocessing` allows multiple `join`s, but this library calls `close` inside `join` [here](https://github.com/celery/billiard/blob/main/billiard/process.py#L147).

I think it should not, but this line of code is 8 years old!
