### ISSUE TITLE
Remove limitation of pytest version

### ISSUE THREAD

**Issue by crazyscientist** [celery/billiard#295]
Hi there,

while messing around with the RPM package for openSUSE, I noticed that the testsuite is running quite well with pytest 5.2.4

Maybe you would care to lift the limitation to pytest versions prior to 5?

**Comment by auvipy** [comment]
can pytest 5.x series test python 2 codes?

**Comment by crazyscientist** [comment]
> can pytest 5.x series test python 2 codes?

Good point.
