### ISSUE TITLE
Support pytest 5

### ISSUE THREAD

**Issue by mrunge** [celery/billiard#297]
Hi,

at least Fedora is moving to pytest 5, billiard requires pytest < 5. 

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ZK25O6CXGKPT7IFAE3SX3WSZCK4KBO7S/#ZK25O6CXGKPT7IFAE3SX3WSZCK4KBO7S

It'd be great if pytest 5 could be supported in billiard.

**Comment by graingert** [comment]
billiard currently supports python 2.7, and pytest~=5 does not

**Comment by graingert** [comment]
@mrunge I made a draft PR to see what happens

**Comment by mrunge** [comment]
Thank you!
