### ISSUE TITLE
WorkerLostError: (Worker exited prematurely: signal 9 (SIGKILL))

### ISSUE THREAD

**Issue by FirojNeosoft** [celery/billiard#302]
Hi,
I got below error while running long task.
Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).')

I used below tools-
celery==4.3.0, amqp==2.5.0, RabbitMQ 3.3.5, AWS EC2 instance as server

I ran 2 long tasks. I got same error for both tasks. 
Then, I converted server type medium to large for EC2 instance, and I got success for one of the 2 tasks. But still one task is not successful due to workerLostError.

**Comment by auvipy** [comment]
use the latest version and report again

**Comment by Beenhakker** [comment]
In my case the container had to less memory, so I needed to increase the resources to 1GB. (running on K8s)

This was quite surprising to me. Initially we had 256MB for a worker, but apparently the baseline is much higher.
We only had this problem with a big, long-running task.

**Comment by igatanasov** [comment]
you just log to k8s container and run https://man7.org/linux/man-pages/man1/dmesg.1.html

and you will see Memory cgroup out of memory: Killed process 2922448 (celery) total-vm:16334160kB, a
