### ISSUE TITLE
AttributeError when terminating Celery worker

### ISSUE THREAD

**Issue by vsemionov** [celery/billiard#306]
After upgrading from version `3.6.1.0` to `3.6.2.0`, the following log event started appearing when terminating the Celery worker:
```
[2020-02-05 10:52:45,723: WARNING/MainProcess] AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by thedrow** [comment]
See https://github.com/celery/billiard/pull/305

**Comment by vsemionov** [comment]
Thank you for the quick pull request!

**Comment by dejlek** [comment]
It would be nice if you make a release with this fix as it is very, very annoying!
