### ISSUE TITLE
Billiard cannot find project module on automatic restart of Celery worker

### ISSUE THREAD

**Issue by professorDante** [celery/billiard#354]
Python 2.7
Billiard 3.3.0.23
Celery 3.1.23

Two workers,  concurrency 2 for each worker. Everything boots up fine from the Docker container. However, once the worker encounters an issue which requires a restart of itself, it suffers an unrecoverable error (see screenshot)

<img width="912" alt="Screen Shot 2022-01-02 at 10 34 53 AM" src="https://user-images.githubusercontent.com/7493788/147885849-7c6a6a99-a581-4838-b399-cfceba0870db.png">

It cannot find the project module. However, starting the worker again manually through the docker container works fine.

**Comment by auvipy** [comment]
please use a recent version of celery. you are using an unsupported old version
