### ISSUE TITLE
NameError on Pool.shrink()

### ISSUE THREAD

**Issue by mschwoer** [celery/billiard#373]
On calling Pool.shrink() I get a `NameError: name 'values' is not defined` (version: 4.0.2).

Seems like `values()` has been introduced quite a while ago (https://github.com/celery/billiard/blob/88ff851b9f97fdba497e6ad7062f76265795f1af/billiard/pool.py), but the import from `.five` has been removed down the line.

*System*
- python 3.8 on MacOS 11.6.8

*Steps to reproduce*
```bash
conda create --name myenv python=3.8
conda activate myenv
pip install billiard==4.0.2
python
```
in the REPL, type
```python
import billiard
p = billiard.Pool()
p.shrink(1)
```

**Comment by auvipy** [comment]
https://github.com/celery/billiard/blob/88ff851b9f97fdba497e6ad7062f76265795f1af/billiard/pool.py#L1285 this line right?

**Comment by auvipy** [comment]
yes I can reproduce it

**Comment by auvipy** [comment]
https://github.com/celery/billiard/blob/88ff851b9f97fdba497e6ad7062f76265795f1af/billiard/pool.py#L1310

**Comment by auvipy** [comment]
related https://github.com/celery/billiard/pull/374

**Comment by mschwoer** [comment]
LGTM
