### ISSUE TITLE
billiard==4.0.2 and celery==5.2.7

### ISSUE THREAD

**Issue by mrjoli021** [celery/billiard#376]
I am upgrading my requirements.txt file.  When I attempt to upgrade to billard==4.0.2 I get a conflict with the celery package.  There is no upgraded package for celery at the moment.

ERROR: Cannot install billiard==4.0.2 and celery==5.2.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested billiard==4.0.2
    celery 5.2.7 depends on billiard<4.0 and >=3.6.4.0

**Comment by auvipy** [comment]
you should try celery 5.3.0b1 with that billiard version
